#18 [12기_문채원] Django tutorial 미션 제출합니다.
CEOS-Developers/django-tutorial-12th pull request #21
Opened 2020-09-18 09:21 UTC by fulladdr

push하는 과정에서 에러 fixing하다가 문제가 생겨서.. 문제가 있을수도있습니다

2020-09-18 09:24 UTC, hanqyu commented
이번 과제해보시면서 느꼈던/배운 점을 본인 폴더에 README.md에 적어 주시면 같이 참고해서 리뷰해드릴게요!

2020-09-19 04:22 UTC, hanqyu requested changes
안녕하세요! 문채원님 리뷰를 맡게된 9기 한규주입니다.

전체적으로 튜토리얼은 어려운 바가 없어서 장고를 한번 돌려보는걸 목표로 하는데, 이번에 좋은 경험이 되셨으리라 믿구요. 이번에는 장고 관련한 것들보다는 git과 관련해서 리뷰를 많이 드릴게요. 풀리퀘를 올릴 경험이 많이 없을테니 참고해주시면 도움 될 것 같습니다.

올라오면 좋지 않거나 필요없는 파일들이 많이 올라와서 커밋 전에 확인하시는 습관을 들여놓는게 좋을 것 같습니다. git stage에 올리기 전에 확인을 하시거나 필요없는 라인이 들어가있는지 확인하시기에는 IDE의 기능을 적극적으로 활용하시는게 좋을 것 같아요. 파이참에서 ctrl + K를 누르시면 관련 기능을 이용하실 수 있습니다.

이번 풀리퀘에서 필요없는 파일들을 제거하고 다시 올리시는게 좋을 것 같아서 풀리퀘 승인은 하지 않도록 하겠습니다.

더불어서 커밋메세지를 잘 정리하는 습관도 지금부터 들이시는 것도 좋을 것 같아요.
이번 과제에서 안내드리지는 않았지만 더 좋은 커밋 메세지를 만들기 위해 추천드리는 방향은 아래와 같습니다.

1. 해당 커밋이 어떤 행위를 하고 있는지
2. 해당 커밋이 어떤 부분을 변경하고 있는지
3. 해당 커밋을 설명하는 메세지, 참고하면 좋을 사항들

을 포함하시는게 좋습니다.

따라서 `part4 made`와 같은 메세지보다는 `feat(view): IndexView, DetailView, ResultsView 추가` 와 같은 메세지가 좋구요, 해당 커밋이 너무 많은 변경점을 가지고 있다고 생각되시면 범위 별로 분류해서
`feat(view): IndexView 추가`
`feat(template): results.html 추가` 로 분리해서 커밋하시는 것도 좋은 습관입니다.

커밋 메세지는 나중의 내가 혹은 다른 협업자가 해당 코드를 수정할때 참고하기에 좋도록 도큐멘테이션을 한다는 생각으로 작성해주시면 아주 좋을거에요.

끝으로 다음 과제를 수행하기전에 이번 과제에서 개선하면 좋을 사항을 추가 드리겠습니다.

1. settings에서 SECRET_KEY 분리하기
- SECRET_KEY는 보안에 중요한 요소이므로 퍼블릭 레포지토리에 노출하면 보안 취약점이 됩니다.
- json이나 yml파일로 분리한 다음 그 파일을 읽어서 SECRET_KEY에 넣도록 하는 방식이 좋을 수도 있고요, django-dotenv나 django-environ와 같은 라이브러리를 이용해서 env 파일을 활용하시는 것도 방법입니다.
- 그리고 그 파일을 gitignore에 추가하면 github에 노출되지 않도록 할 수 있겠지요.

2. ForeignKey에서 related_name 이용하기
- Choice모델을 참고하시면 되는데 ForeignKey에 related_name을 넣지 않는다면 django가 자동으로 만들어줍니다. ex. choice_set
- related_name은 생각보다 많이 쓰게 되는데, 본인이 편한 네이밍으로 수정하면 좀 더 편하고 가독성 있는 코드가 되겠죠?
- 보통은 choices와 같이 복수형으로 표현하는걸 권장합니다.

간단하지만 꼭 필요할 것 같은 내용들을 말씀드렸구요, 여유가 된다면 적용해보시는 것도 좋을 것 같습니다. 특히 1번 내용에서 라이브러리를 이용하여 개선해보신다면 좋은 경험이 될 듯 하네요!

수고하셨구요, 다음 스터디에서 뵙겠습니다 👍

2020-09-19 04:22 UTC, hanqyu commented on .gitignore
> -*/.idea/
루트 폴더의 .gitignore를 삭제하시면 안돼요~ 공용이라서 루트 폴더의 것들은 남겨두셔야 합니다!

2020-09-19 04:22 UTC, hanqyu commented on .idea/.gitignore
> +# Default ignored files
.idea와 __pycache__도 같이 올라오게 됐는데 이 부분은 gitignore에 추가하시는게 좋습니다.
오로지 로컬환경만을 위한 파일이기 때문에 공유하면 계속 충돌이 발생해서 생산성에 좋지 않을거에요

2020-09-20 06:03 UTC, hanqyu commented
채원님! 보시면 맨 아래에 conflict가 있어서 머지가 불가능하다고 하는데요, 보시면 readme를 작성해주신 게 본인의 폴더가 아닌 루트 폴더의 readme를 작성해주셔서 해당 부분을 수정해주시고 다시 푸시해주시면 머지가능할 것 같습니다! @fulladdr

2020-09-20 06:04 UTC, fulladdr commented
넵넵 확인해서 다시 보내드리도록 하겠습니다

2020년 9월 20일 (일) 오후 3:03, KyuJoo Han <notifications@github.com>님이 작성:

> 채원님! 보시면 맨 아래에 conflict가 있어서 머지가 불가능하다고 하는데요, 보시면 readme를 작성해주신 게 본인의 폴더가
> 아닌 루트 폴더의 readme를 작성해주셔서 해당 부분을 수정해주시고 다시 푸시해주시면 머지가능할 것 같습니다! @fulladdr
> <https://github.com/fulladdr>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CEOS-Developers/django-tutorial-12th/pull/21#issuecomment-695749753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANX6EQG7F446YV4ADKWFMA3SGWLMDANCNFSM4RRWO5DA>
> .
>

2020-09-20 06:06 UTC, fulladdr commented
혹시 방금 README 부분을 다시 제 폴더 안에 넣어서 push했는데 이렇게 되면 업데이트가 되는건가요??

깃허브 사용이 익숙치 않아 헷갈리네요..!

2020년 9월 20일 (일) 오후 3:03, KyuJoo Han <notifications@github.com>님이 작성:

> 채원님! 보시면 맨 아래에 conflict가 있어서 머지가 불가능하다고 하는데요, 보시면 readme를 작성해주신 게 본인의 폴더가
> 아닌 루트 폴더의 readme를 작성해주셔서 해당 부분을 수정해주시고 다시 푸시해주시면 머지가능할 것 같습니다! @fulladdr
> <https://github.com/fulladdr>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CEOS-Developers/django-tutorial-12th/pull/21#issuecomment-695749753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANX6EQG7F446YV4ADKWFMA3SGWLMDANCNFSM4RRWO5DA>
> .
>

2020-09-20 08:19 UTC, justzino approved these changes
master branch로 merge 해드립니다.

2020-09-20 08:22 UTC, merged